# Generated by Django 4.0.4 on 2022-04-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_chinese_full_name_product_chinese_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='meat',
            field=models.CharField(choices=[('Duck', 'Duck'), ('Chicken', 'Chicken'), ('Pork', 'Pork'), ('Egg', 'Egg'), ('Meatless', 'Meatless')], default='Duck', max_length=8),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Warm', 'Warm'), ('Frozen', 'Frozen'), ('Ingredient', 'Ingredient')], default='Warm', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='chinese_full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='chinese_name',
            field=models.CharField(max_length=255),
        ),
    ]
