# Generated by Django 4.0.4 on 2022-04-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_meat_product_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='meat',
            field=models.CharField(choices=[('Duck', 'Duck'), ('Chicken', 'Chicken'), ('Pork', 'Pork'), ('Egg', 'Egg'), ('Meatless', 'Meatless')], max_length=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Warm', 'Warm'), ('Frozen', 'Frozen'), ('Ingredient', 'Ingredient')], max_length=10),
        ),
    ]
