# Generated by Django 4.0.4 on 2022-04-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_meat_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='chinese_full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='meat',
            field=models.CharField(blank=True, choices=[('Duck', 'Duck'), ('Chicken', 'Chicken'), ('Pork', 'Pork'), ('Egg', 'Egg'), ('Meatless', 'Meatless')], max_length=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, choices=[('Warm', 'Warm'), ('Frozen', 'Frozen'), ('Ingredient', 'Ingredient')], max_length=10),
        ),
    ]
